name: Dolphin-CI

on:
  push:
    branches: [ meponderR-patch-1 ]
  pull_request:
    branches: [ meponderR-patch-1 ]

jobs:
  ios:
    name: ios
    
    runs-on: macOS-latest
    
    steps:
    - name: Checkout Dolphin
      uses: actions/checkout@v2.1.0
      
    - name: Install dependencies
      run: |
        brew install ninja bartycrouch dpkg libmagic ldid
        pip3 install polib python-magic
        pod install
      working-directory: ./Source/iOS/DolphiniOS

    - name: Setup Workspace
      run: |
           rm DolphiniOS/BuildResources/BuildScripts/UpdateEntitlements.sh
           touch DolphiniOS/BuildResources/BuildScripts/UpdateEntitlements.sh
           chmod 755 DolphiniOS/BuildResources/BuildScripts/UpdateEntitlements.sh
           curl https://cdn.oatmealdome.me/dolphinios/ipa/DolphiniOS-NJB-2.2.2-1.ipa -o dolphinr.ipa
           unzip -q dolphinr.ipa -d releaseipa/
           cp -r releaseipa/Payload/DolphiniOS.app/GoogleService-Info.plist DolphiniOS/GoogleService-Info.plist
           mkdir ipas
      working-directory: ./Source/iOS/DolphiniOS

    - name: Compile non-jailbroken ipa
      run: |
           xcodebuild archive -workspace DolphiniOS.xcworkspace -scheme DolphiniOS -archivePath DolphiniOS-njb.xcarchive -configuration "Debug (Non-Jailbroken)" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
           cp -r DolphiniOS-njb.xcarchive/Products/Applications/ Payload/
           echo "Start Codesign"
           ldid -SDolphiniOS/BuildResources/Entitlements_PsychicPaper_Release.plist Payload/DolphiniOS.app/DolphiniOS
           ldid -SDolphiniOS/BuildResources/Entitlements_PsychicPaper_Release.plist Payload/DolphiniOS.app/Frameworks/*
           echo "End Codesign"
           zip -q -r ipas/Dolphin-njb.ipa Payload
           rm -r Payload/
      working-directory: ./Source/iOS/DolphiniOS
      
    - name: Upload non-jailbroken ipa
      uses: actions/upload-artifact@v2
      with:
        name: DolphiniOS Beta (Non-Jailbroken)
        path: Source/iOS/DolphiniOS/ipas/Dolphin-njb.ipa
      
    - name: Compile jailbroken App
      run: |
          xcodebuild archive -workspace DolphiniOS.xcworkspace -scheme DolphiniOS -archivePath DolphiniOS-jb.xcarchive -configuration "Debug (Jailbroken)" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
          BUNDLE_ID="me.oatmealdome.DolphiniOS"
          VERSION_STRING=$(cat DolphiniOS.xcodeproj/project.pbxproj | grep -m1 'MARKETING_VERSION' | cut -d'=' -f2 | tr -d ';' | tr -d ' ')
          BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "DolphiniOS/Info.plist")
          
          
          echo "Copy to DEB dir" 
          mkdir -p "JBEX/DEBIAN"
          sudo cp -r "DolphiniOS-jb.xcarchive/Products/Applications" "JBEX/Applications"
          echo "Copy deb files"
          sudo cp DolphiniOS/BuildResources/DebFiles/postinst.sh JBEX/DEBIAN/postinst
          sudo cp DolphiniOS/BuildResources/DebFiles/postrm.sh JBEX/DEBIAN/postrm
          echo "Chmod"
          sudo chmod -R 755 JBEX/DEBIAN/*
          echo "ldid Executable File"
          ldid -SDolphiniOS/BuildResources/Entitlements_JB.plist ./JBEX/Applications/DolphiniOS.app/DolphiniOS
          echo "ldid Library Files"
          ldid -SDolphiniOS/BuildResources/Entitlements_JB.plist ./JBEX/Applications/DolphiniOS.app/Frameworks/*
          echo "Replace version"
          sudo sed "s/VERSION_NUMBER/$VERSION_STRING-$BUILD_NUMBER/g" DolphiniOS/BuildResources/DebFiles/control.in > JBEX/DEBIAN/control
          sudo plutil -replace "CFBundleIdentifier" -string "$BUNDLE_ID" JBEX/Applications/DolphiniOS.app/Info.plist
          echo "dpkg"
          sudo dpkg-deb -b JBEX
          sudo mv JBEX.deb DolphiniOS-$VERSION_STRING.deb
          echo "::set-env name=DebName::DolphiniOS-$VERSION_STRING.deb"
          echo "Done"
           
           
      working-directory: ./Source/iOS/DolphiniOS
      
    - name: Upload jailbroken deb
      uses: actions/upload-artifact@v2
      with:
        name: DolphiniOS Beta (Jailbroken)
        path: ./Source/iOS/DolphiniOS/${{env.DebName}}
